//
//  FSEventMonitor+Options.swift
//  
//
//  Created by Florian Zand on 26.01.25.
//

#if os(macOS)
import Foundation

extension FSEventMonitor {
    /// Options for monitoring.
    public struct Options: OptionSet, Hashable {
        /**
         Monitors for changes along the path of the file urls you're watching.
         
         For example, if you watch `/foo/folder1/bar` and it is moved to `/foo/folder2/bar`, you would receive a `rootChanged` event.

         The `rootChanged` event contains the original file url, that may no longer exist because it or one of its parents was deleted or renamed.
         
         The event is useful to indicate that you should rescan a particular hierarchy because it changed completely (as opposed to the things inside of it changing). If you want to track the current location of a directory, it is best to open the directory before monitoring the files so that you have a file descriptor for it.
         */
        public static let monitorRoot = Self(kFSEventStreamCreateFlagWatchRoot)
        
        /// Monitors for changes 
        public static let monitorFolderContent = Self(1 << 100)
        
        /**
         Ignore events generated by this process.

         This is useful for reducing the volume of events that are sent. It is only useful if your process might modify the file system hierarchy beneath the path(s) being monitored. Note: this has no effect on `historical` events, i.e., those delivered before the `historyDone` sentinel event.
         */
        public static let ignoreSelf = Self(kFSEventStreamCreateFlagIgnoreSelf)
                
        /**
         This option ensures that events are delivered immediately if more than the specified ``FSEventMonitor/latency`` seconds
         have passed since the last event, bypassing any deferral or batching.
                           
         If you specify this option and more than the specified ``FSEventMonitor/latency`` seconds have elapsed since the last event, the callback handler will receive the event immediately. The delivery of the event resets the latency timer and any further events will be delivered after `latency` seconds have elapsed.
         
         This flag is useful for apps that are interactive and want to react immediately to changes but avoid getting swamped by notifications when changes are occurringin rapid succession.
         
         If you do not specify this option, then when an event occurs after a period of no events, the latency timer is started. Any events that occur during the next `latency` seconds will be delivered to the callback handler. The delivery of events resets the latency timer and any further events will be delivered after `latency` seconds. This is the default behavior and is more appropriate for background, daemon or batch processing apps.
         */
        public static let noDefer = Self(kFSEventStreamCreateFlagNoDefer)
        
        /**
         Include the full history of all events.
         
         If you include this option, the event monitor provides all past events for it's monitored file urls on start.
        */
        public static let includeFullHistory = Self(kFSEventStreamCreateFlagFullHistory)
        
        static let useCFTypes = Self(kFSEventStreamCreateFlagUseCFTypes)
        static let fileEvents = Self(kFSEventStreamCreateFlagFileEvents)
        static let extendedData = Self(kFSEventStreamCreateFlagUseExtendedData)
        static let markSelf = Self(kFSEventStreamCreateFlagMarkSelf)
                
        var flags: UInt32 {
            var options = self
            options.insert([.useCFTypes, .fileEvents, .extendedData])
            options.remove(.monitorFolderContent)
            if !options.contains(.ignoreSelf) { options.insert(.markSelf) }
            return options.rawValue
        }
        
        public let rawValue: UInt32
        
        public init(rawValue: UInt32) {
            self.rawValue = rawValue
        }
        init(_ rawValue: Int) {
            self.rawValue = UInt32(rawValue)
        }
    }
}
#endif
